services:
  - type: web
    name: anythingllm-web
    env: docker
    repo: https://github.com/bhilliardga/anything-llm
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    healthCheckPath: /health

  - type: worker
    name: anythingllm-collector
    env: docker
    repo: https://github.com/bhilliardga/anything-llm
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    dockerCommand: npm run collector
